version: '3.8'

services:
  mongodb:
    image: mongo:8.2.1
    container_name: addis_music_db_dev
    environment:
      MONGO_INITDB_ROOT_USERNAME: usr_db_addis_music
      MONGO_INITDB_ROOT_PASSWORD: pass_db_addis_music
      MONGO_INITDB_DATABASE: db_addis_music
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_dev:/data/db
    networks:
      - addis_music_network

  backend:
    build:
      context: ../be_addis_music
      dockerfile: Dockerfile
    container_name: addis_music_backend_dev
    environment:
      PORT: 3000
      MONGODB_URI: mongodb://usr_db_addis_music:pass_db_addis_music@mongodb:27017/db_addis_music?authSource=admin
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    networks:
      - addis_music_network
    restart: unless-stopped

  frontend:
    build:
      context: ../fe_addis_music
      dockerfile: Dockerfile
    container_name: addis_music_frontend_dev
    environment:
      VITE_API_BASE_URL: http://localhost:3000/api
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - addis_music_network

volumes:
  mongodb_data_dev:

networks:
  addis_music_network:
    driver: bridge